name: Publish ADR Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/adr/**'
      - '.github/workflows/adr-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup direnv
        uses: HatsuneMiku3939/direnv-action@v1

      - name: Build ADR documentation
        run: |
          direnv allow
          direnv exec . npm ci
          direnv exec . npm run adr:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .log4brains/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}adr/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4